# Generated by Django 5.2.13 on 2026-05-12 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTickerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_price_inr_per_gram_22k', models.DecimalField(decimal_places=2, default=Decimal('7245.50'), max_digits=12)),
                ('admin_markup_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gold ticker configuration',
            },
        ),
        migrations.CreateModel(
            name='JewellerPricingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gold_markup_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('sellback_deduction_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('sellback_fixed_inr_per_gram', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gold_deposit_note', models.TextField(blank=True, help_text='Shown on marketplace for vault/gold deposit policies.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jeweller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jeweller_pricing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=80)),
                ('gold_weight_grams', models.DecimalField(decimal_places=3, max_digits=10)),
                ('making_charge_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.URLField(max_length=512)),
                ('pricing_mode', models.CharField(choices=[('spot_markup', 'Spot base + markup'), ('manual_rate', 'Manual gold rate / gram')], default='spot_markup', max_length=20)),
                ('jeweller_markup_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Overrides jeweller default spot markup when set.', max_digits=8, null=True)),
                ('manual_gold_rate_inr_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stone_included', models.BooleanField(default=False)),
                ('stone_type', models.CharField(blank=True, max_length=120)),
                ('stone_weight_grams', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('stone_cost_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_x_redeem', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3)),
                ('is_published', models.BooleanField(default=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jeweller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
