# Generated by Django 5.2.13 on 2026-05-12 08:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellerpricingprofile',
            name='buyback_headline_inr_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional headline buyback ₹/g; when empty, indicative buyback is derived from metal rate and sellback deductions.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jewellerpricingprofile',
            name='gold_deposit_yield_apr_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Disclosed annual yield % on gold deposit / saver schemes (storefront only).', max_digits=8),
        ),
        migrations.AddField(
            model_name='jewellerpricingprofile',
            name='gold_loan_interest_apr_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Disclosed annual interest % on gold-backed loans (storefront only).', max_digits=8),
        ),
        migrations.AddField(
            model_name='jewellerpricingprofile',
            name='representative_making_charge_inr_per_gram',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Typical making charge (₹/g) used for jeweller comparison cards and sorting.', max_digits=12),
        ),
    ]
