# Generated by Django 5.2.13 on 2026-05-12 20:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_gold_rate_move_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellerpricingprofile',
            name='live_markup_inr_per_gram',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Extra ₹/g after percent, on Cridora live 22K.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='jewellerpricingprofile',
            name='live_markup_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Percent markup on Cridora live 22K (before default per-SKU markup).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='jewellerpricingprofile',
            name='manual_gold_rate_inr_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed 22K ₹/g for all spot-linked pricing when source is manual.', max_digits=12, null=True),
        ),
    ]
