# Generated by Django 5.2.13 on 2026-05-15 07:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_goldtickerconfig_cross_platform_fee_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldtickerconfig',
            name='admin_markup_inr_per_gram',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deprecated — use live_metal_adjustments_json.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='goldtickerconfig',
            name='admin_markup_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Deprecated — use live_metal_adjustments_json.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='goldtickerconfig',
            name='reference_price_inr_per_gram_22k',
            field=models.DecimalField(decimal_places=2, default=Decimal('7245.50'), help_text='Legacy fallback raw 22K ₹/g only when no live snapshot exists.', max_digits=12),
        ),
    ]
