# Generated by Django 5.2.13 on 2026-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_catalogue_purity_category_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='same_store_making_charge_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='When making_charge_mode is percent: making charge as percent of gold metal for customers whose default jeweller is this listing jeweller.', max_digits=8, null=True),
        ),
    ]
