# Generated by Django 5.2.13 on 2026-05-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_marketplaceproduct_same_store_making_charge_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTickerReferenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inr_per_gram_22k', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_source', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Gold ticker reference history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
