# Generated by Django 5.2.13 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0026_gold_loan_max_term_months"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldRateDailySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField(db_index=True, unique=True)),
                ("open_inr", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high_inr", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low_inr", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close_inr", models.DecimalField(decimal_places=2, max_digits=12)),
                ("change_inr", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("change_pct", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ("base_source", models.CharField(blank=True, default="", max_length=64)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Gold rate daily snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
    ]
