# Generated by Django 5.2.13 on 2026-05-29 18:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_gold_rate_history_portfolio_gain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldratehistory',
            name='jeweller',
            field=models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='gold_rate_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goldtickerconfig',
            name='enable_fun_notifications',
            field=models.BooleanField(default=False, help_text='Allow occasional fun/time-of-day notification copy (max 1/day per user).'),
        ),
        migrations.AlterField(
            model_name='goldtickerconfig',
            name='portfolio_gain_threshold_inr',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Notify customers when portfolio value gain vs cost basis exceeds this ₹ amount.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='goldtickerconfig',
            name='portfolio_gain_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Or when gain percentage exceeds this value (whichever triggers first).', max_digits=8),
        ),
    ]
