# Generated by Django 5.2.13 on 2026-05-30 19:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_alter_goldratehistory_jeweller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goldtickerconfig',
            name='holding_gain_threshold_inr',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Per personal holding: notify when estimated value gain vs last notified baseline exceeds this ₹.', max_digits=14),
        ),
        migrations.AddField(
            model_name='goldtickerconfig',
            name='max_gold_alerts_per_day',
            field=models.PositiveSmallIntegerField(default=3, help_text='Max gold-rate / holding gain inbox+push alerts per customer per day.'),
        ),
        migrations.AlterField(
            model_name='goldratehistory',
            name='jeweller',
            field=models.ForeignKey(blank=True, help_text='Null for platform Cridora 22K reference moves.', limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_rate_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
