# Generated by Django 5.2.13 on 2026-06-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_gold_rates_page_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldratesadplacement',
            name='adsense_format',
            field=models.CharField(blank=True, default='auto', help_text='AdSense data-ad-format, e.g. auto, horizontal, rectangle.', max_length=24),
        ),
        migrations.AlterField(
            model_name='goldratesadplacement',
            name='adsense_slot_id',
            field=models.CharField(blank=True, default='', help_text='AdSense ad unit slot ID when mode is AdSense.', max_length=64),
        ),
        migrations.AlterField(
            model_name='goldratesadplacement',
            name='manual_html',
            field=models.TextField(blank=True, default='', help_text='Raw HTML for sponsored blocks (admin-reviewed only).'),
        ),
        migrations.AlterField(
            model_name='goldratespageconfig',
            name='adsense_client_id',
            field=models.CharField(blank=True, default='', help_text='Google AdSense publisher ID, e.g. ca-pub-xxxxxxxx.', max_length=64),
        ),
        migrations.AlterField(
            model_name='goldratespageconfig',
            name='adsense_enabled',
            field=models.BooleanField(default=False, help_text='When on, active AdSense placements render using the client ID below.'),
        ),
    ]
