# Generated by Django 5.2.13 on 2026-06-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_gold_push_tap_link_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcalculatoradplacement',
            name='manual_html',
            field=models.TextField(blank=True, default='', help_text='Raw HTML for sponsored blocks (admin-reviewed only).'),
        ),
        migrations.AlterField(
            model_name='goldcalculatorpageconfig',
            name='adsense_client_id',
            field=models.CharField(blank=True, default='', help_text='Google AdSense publisher ID, e.g. ca-pub-xxxxxxxx.', max_length=64),
        ),
        migrations.AlterField(
            model_name='goldcalculatorpageconfig',
            name='adsense_enabled',
            field=models.BooleanField(default=False, help_text='When on, active AdSense placements render using the client ID below.'),
        ),
    ]
