# Generated by Django 5.2.13 on 2026-06-14 05:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JewellerSchemeOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('customer_facing_note', models.TextField(blank=True)),
                ('jeweller_overrides', models.JSONField(blank=True, default=dict)),
                ('design_snapshot', models.JSONField(blank=True, default=dict)),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSchemeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('plan_month_complete', 'Plan month complete'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], db_index=True, default='active', max_length=32)),
                ('current_cycle_number', models.PositiveIntegerField(default=1)),
                ('current_plan_month', models.PositiveSmallIntegerField(default=1)),
                ('cycle_anchor_date', models.DateField()),
                ('design_snapshot', models.JSONField(blank=True, default=dict)),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_enrollments', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schemes.jewellerschemeoffering')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('calendar_month', models.CharField(max_length=7)),
                ('deposit_sequence_in_month', models.PositiveSmallIntegerField(default=1)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gold_grams', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('gold_value_inr_pre_gst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=3, default=Decimal('3'), max_digits=6)),
                ('gst_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('making_charge_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('metal_rate_inr_per_gram', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('counter', 'Pay at counter')], max_length=16)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('signal_received', 'Payment signal received'), ('awaiting_counter', 'Awaiting counter confirmation'), ('awaiting_utr_verify', 'Awaiting UTR verification'), ('pending_review', 'Pending jeweller review'), ('needs_manual_verification', 'Needs manual verification'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('proof_rejected', 'Proof rejected'), ('on_hold', 'On hold')], default='pending_payment', max_length=32)),
                ('customer_note', models.CharField(blank=True, max_length=255)),
                ('payee_upi_vpa', models.CharField(blank=True, max_length=128)),
                ('payment_note', models.CharField(blank=True, max_length=128)),
                ('payment_expires_at', models.DateTimeField(blank=True, null=True)),
                ('upi_utr', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('utr_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reconciliation_flags', models.JSONField(blank=True, default=dict)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('jeweller_verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_contributions_confirmed', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='schemes.customerschemeenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeContributionCounterOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_otp', to='schemes.schemecontribution')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeMonthBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('month_index', models.PositiveSmallIntegerField()),
                ('calendar_month', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('monthly_total_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('monthly_total_grams', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('deposit_count', models.PositiveIntegerField(default=0)),
                ('is_customer_month', models.BooleanField(default=True)),
                ('is_bonus_month', models.BooleanField(default=False)),
                ('bonus_computed_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_buckets', to='schemes.customerschemeenrollment')),
            ],
            options={
                'ordering': ['cycle_number', 'month_index'],
            },
        ),
        migrations.CreateModel(
            name='SchemeLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('entry_kind', models.CharField(choices=[('contribution_inr', 'Contribution INR'), ('contribution_gold', 'Contribution gold'), ('jeweller_bonus_inr', 'Jeweller bonus INR'), ('jeweller_bonus_gold', 'Jeweller bonus gold'), ('making_charge_credit_inr', 'Making charge credit'), ('making_charge_credit_applied', 'MC credit applied'), ('redemption_debit_inr', 'Redemption debit INR'), ('redemption_debit_gold', 'Redemption debit gold'), ('month_bucket_close', 'Month bucket close'), ('cycle_rollover', 'Cycle rollover')], max_length=40)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gold_grams', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='schemes.schemecontribution')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='schemes.customerschemeenrollment')),
                ('month_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='schemes.schememonthbucket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='schemecontribution',
            name='month_bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='schemes.schememonthbucket'),
        ),
        migrations.CreateModel(
            name='SchemeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('otp_issued', 'OTP issued'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redeem_as', models.CharField(default='jewellery_cash_pool', max_length=40)),
                ('amount_inr_from_pool', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gold_grams_debited', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('making_charge_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('mc_credit_applied_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('topup_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('quote_snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='schemes.customerschemeenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='general', max_length=80)),
                ('icon_key', models.CharField(blank=True, default='scheme', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('scheme_design', models.JSONField(blank=True, default=dict)),
                ('scheme_rules', models.JSONField(blank=True, default=dict)),
                ('flow_summary', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scheme_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('proposed_terms', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs info')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scheme_requests', to=settings.AUTH_USER_MODEL)),
                ('jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_requests', to=settings.AUTH_USER_MODEL)),
                ('resulting_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_requests', to='schemes.schemetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jewellerschemeoffering',
            name='scheme_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jeweller_offerings', to='schemes.schemetemplate'),
        ),
        migrations.CreateModel(
            name='SchemeCycleBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField()),
                ('bonus_month_index', models.PositiveSmallIntegerField()),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gold_grams', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('credit_as', models.CharField(default='cash_pool', max_length=32)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending jeweller confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_scheme_bonuses', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_bonuses', to='schemes.customerschemeenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'cycle_number'), name='uniq_enrollment_cycle_bonus')],
            },
        ),
        migrations.AddConstraint(
            model_name='schememonthbucket',
            constraint=models.UniqueConstraint(fields=('enrollment', 'cycle_number', 'calendar_month'), name='uniq_enrollment_cycle_calendar_month'),
        ),
        migrations.AddConstraint(
            model_name='jewellerschemeoffering',
            constraint=models.UniqueConstraint(fields=('jeweller', 'scheme_template'), name='uniq_jeweller_scheme_template_offering'),
        ),
    ]
