"""Saga step names and outbox types (cross-redemption MVP)."""

STEP_VAULT_TRANSFER = "VAULT_TRANSFER"
STEP_LIABILITY_SOURCE_RELEASE = "LIABILITY_SOURCE_RELEASE"
STEP_LIABILITY_DEST_ASSUME = "LIABILITY_DEST_ASSUME"
STEP_SETTLEMENT_OBLIGATION = "SETTLEMENT_OBLIGATION"
STEP_OUTBOX_NOTIFY = "OUTBOX_NOTIFY"

ORDERED_FORWARD_STEPS = (
    STEP_VAULT_TRANSFER,
    STEP_LIABILITY_SOURCE_RELEASE,
    STEP_LIABILITY_DEST_ASSUME,
    STEP_SETTLEMENT_OBLIGATION,
    STEP_OUTBOX_NOTIFY,
)

OUTBOX_CROSS_REDEMPTION_NOTIFY = "cross_redemption.notify_parties"
