from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    BankAccountUpsertView,
    CustomerPersonalProfileView,
    CustomerRegisterView,
    HealthView,
    JewellerApplyView,
    JewellerBusinessProfileView,
    KYDocumentListView,
    KYDocumentUploadView,
    LoginView,
    LogoutView,
    MeView,
    PasswordChangeView,
    ProfilePhotoView,
)
from .views_jeweller_portfolio import JewellerPortfolioLedgerView
from .views_gold import (
    DefaultJewellerView,
    GoldIdentityUpsertView,
    GoldTransferCreateView,
    GoldTransferPublicMetaView,
    GoldUPIResolveView,
    GoldWalletView,
    JewellerCustodyVaultsView,
    JewellerCustomerVaultLedgerView,
)
from .views_admin import (
    AdminCustomerKYCActionView,
    AdminDocumentRequestReuploadView,
    AdminFreezeUserView,
    AdminFractionalCounterOtpPolicyView,
    AdminJewellerKYBActionView,
    AdminNotificationsListView,
    AdminNotificationsMarkReadView,
    AdminOverviewView,
    AdminUserDocumentsView,
    AdminVerificationRevokeView,
)
from .fractional_views import (
    FractionalCounterOtpIssueView,
    FractionalCounterOtpPolicyView,
    FractionalOrderConfirmUpiView,
    FractionalOrdersView,
    FractionalQuoteView,
    JewellerFractionalPendingView,
    JewellerFractionalVerifyView,
)
from .fractional_upi_views import (
    FractionalOrderCancelUpiView,
    FractionalOrderPaymentView,
    FractionalOrderSubmitUtrView,
    JewellerFractionalConfirmUtrView,
    JewellerFractionalPendingUpiView,
    JewellerUpiProfileView,
)
from .gold_deposit_views import (
    CustomerGoldDepositCounterOtpIssueView,
    CustomerGoldDepositIntakesView,
    JewellerGoldDepositIntakeCreateView,
    JewellerGoldDepositPendingView,
    JewellerGoldDepositVerifyView,
)
from .loan_views import (
    GoldLoanCompareView,
    GoldLoanVaultRatesView,
    GoldLoanAccountsView,
    GoldLoanConfirmView,
    GoldLoanOutstandingView,
    GoldLoanOtpRegenerateView,
    GoldLoanRepayView,
    GoldLoanRepaymentCancelView,
    GoldLoanRepaymentOtpRegenerateView,
    GoldLoanQuoteView,
    JewellerLoanAcceptView,
    JewellerLoanCompleteView,
    JewellerLoanListView,
    JewellerLoanRejectView,
    JewellerLoanRepaymentAcceptView,
    JewellerLoanRepaymentCompleteView,
    JewellerLoanRepaymentListView,
    JewellerLoanRepaymentRejectView,
)
from .sellback_views import (
    GoldSellbackConfirmView,
    GoldSellbackOutstandingView,
    GoldSellbackOtpRegenerateView,
    GoldSellbackQuoteView,
    JewellerSellbackAcceptView,
    JewellerSellbackCompleteView,
    JewellerSellbackListView,
    JewellerSellbackRejectView,
)
from .sellback_upi_views import (
    CustomerPayoutUpiProfileView,
    CustomerSellbackCancelUpiView,
    CustomerSellbackConfirmUtrView,
    JewellerSellbackPayoutView,
    JewellerSellbackSubmitUtrView,
)
from .views_festival_broadcast import (
    AdminFestivalBroadcastCancelView,
    AdminFestivalBroadcastListCreateView,
)
from .views_platform_notifications import (
    PlatformNotificationsListView,
    PlatformNotificationsMarkReadView,
)
from .views_push import (
    NativePushStatusView,
    NativePushSubscribeView,
    NativePushUnsubscribeView,
    WebPushAdminSelfTestView,
    WebPushSubscribeView,
    WebPushUnsubscribeView,
    WebPushVapidPublicKeyView,
)
from .views_personal_portfolio import (
    AdminPersonalDocumentRemoveView,
    AdminPersonalHoldingRemoveView,
    AdminPersonalHoldingsListView,
    AdminPersonalHoldingVerifyView,
    CustomerPortfolioLedgerView,
    JewellerCustomerLookupView,
    JewellerPersonalHoldingCreateView,
    PersonalHoldingDetailView,
    PersonalHoldingDocumentDeleteView,
    PersonalHoldingDocumentDownloadView,
    PersonalHoldingDocumentsCreateView,
    PersonalHoldingsListCreateView,
    PersonalVaultDocumentsListView,
    PortfolioUserNotificationsListView,
    PortfolioUserNotificationsMarkReadView,
)
from .cross_redemption_views import (
    AdminCrossRedemptionListView,
    AdminCrossRedemptionRiskBlockView,
    AdminCrossRedemptionSettlementCompleteView,
    CustomerCrossRedemptionAuthorizeView,
    CustomerCrossRedemptionCancelView,
    CustomerCrossRedemptionListView,
    JewellerCrossRedemptionDestAcceptView,
    JewellerCrossRedemptionDestRejectView,
    JewellerCrossRedemptionFulfillmentHeartbeatView,
    JewellerCrossRedemptionInboxView,
    JewellerCrossRedemptionInitiateView,
    JewellerCrossRedemptionSourceApproveView,
    JewellerCrossRedemptionSourceOtpView,
    JewellerCrossRedemptionSourceRejectView,
)
urlpatterns = [
    path("portfolio/ledger/", CustomerPortfolioLedgerView.as_view()),
    path("portfolio/notifications/", PortfolioUserNotificationsListView.as_view()),
    path("portfolio/notifications/mark-read/", PortfolioUserNotificationsMarkReadView.as_view()),
    path("portfolio/personal-holdings/", PersonalHoldingsListCreateView.as_view()),
    path("portfolio/personal-holdings/documents/", PersonalVaultDocumentsListView.as_view()),
    path("portfolio/personal-holdings/<int:pk>/", PersonalHoldingDetailView.as_view()),
    path(
        "portfolio/personal-holdings/<int:holding_pk>/documents/",
        PersonalHoldingDocumentsCreateView.as_view(),
    ),
    path(
        "portfolio/personal-holdings/<int:holding_pk>/documents/<int:doc_pk>/",
        PersonalHoldingDocumentDeleteView.as_view(),
    ),
    path(
        "portfolio/personal-holdings/<int:holding_pk>/documents/<int:doc_pk>/download/",
        PersonalHoldingDocumentDownloadView.as_view(),
    ),
    path("jeweller/customers/lookup/", JewellerCustomerLookupView.as_view()),
    path("jeweller/personal-holdings/", JewellerPersonalHoldingCreateView.as_view()),
    path("admin/personal-holdings/", AdminPersonalHoldingsListView.as_view()),
    path("admin/personal-holdings/<int:pk>/remove/", AdminPersonalHoldingRemoveView.as_view()),
    path("admin/personal-holdings/<int:pk>/verify/", AdminPersonalHoldingVerifyView.as_view()),
    path(
        "admin/personal-holdings/<int:holding_pk>/documents/<int:doc_pk>/remove/",
        AdminPersonalDocumentRemoveView.as_view(),
    ),
    path("admin/festival-broadcasts/", AdminFestivalBroadcastListCreateView.as_view()),
    path(
        "admin/festival-broadcasts/<int:pk>/cancel/",
        AdminFestivalBroadcastCancelView.as_view(),
    ),
    path("push/vapid-public-key/", WebPushVapidPublicKeyView.as_view()),
    path("push/subscribe/", WebPushSubscribeView.as_view()),
    path("push/unsubscribe/", WebPushUnsubscribeView.as_view()),
    path("push/native-status/", NativePushStatusView.as_view()),
    path("push/native-subscribe/", NativePushSubscribeView.as_view()),
    path("push/native-unsubscribe/", NativePushUnsubscribeView.as_view()),
    path("notifications/", PlatformNotificationsListView.as_view()),
    path("notifications/mark-read/", PlatformNotificationsMarkReadView.as_view()),
    path("admin/push/test/", WebPushAdminSelfTestView.as_view()),
    path("health/", HealthView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/register/", CustomerRegisterView.as_view()),
    path("auth/jeweller/apply/", JewellerApplyView.as_view()),
    path("auth/me/", MeView.as_view()),
    path("auth/profile-photo/", ProfilePhotoView.as_view()),
    path("auth/password/change/", PasswordChangeView.as_view()),
    path("jeweller/business-profile/", JewellerBusinessProfileView.as_view()),
    path("gold/wallet/", GoldWalletView.as_view()),
    path("gold/loans/vault-rates/", GoldLoanVaultRatesView.as_view()),
    path("gold/loans/compare/", GoldLoanCompareView.as_view()),
    path("gold/loans/quote/", GoldLoanQuoteView.as_view()),
    path("gold/loans/confirm/", GoldLoanConfirmView.as_view()),
    path("gold/loans/outstanding/", GoldLoanOutstandingView.as_view()),
    path("gold/loans/accounts/", GoldLoanAccountsView.as_view()),
    path("gold/loans/<int:pk>/repay/", GoldLoanRepayView.as_view()),
    path("gold/loans/<int:pk>/otp/regenerate/", GoldLoanOtpRegenerateView.as_view()),
    path(
        "gold/loans/repayments/<int:pk>/otp/regenerate/",
        GoldLoanRepaymentOtpRegenerateView.as_view(),
    ),
    path(
        "gold/loans/repayments/<int:pk>/cancel/",
        GoldLoanRepaymentCancelView.as_view(),
    ),
    path("gold/sellback/quote/", GoldSellbackQuoteView.as_view()),
    path("gold/sellback/confirm/", GoldSellbackConfirmView.as_view()),
    path("gold/sellback/outstanding/", GoldSellbackOutstandingView.as_view()),
    path("gold/sellback/<int:pk>/otp/regenerate/", GoldSellbackOtpRegenerateView.as_view()),
    path("customer/profile/", CustomerPersonalProfileView.as_view()),
    path("customer/profile/payout-upi/", CustomerPayoutUpiProfileView.as_view()),
    path("gold/sellback/<int:pk>/confirm-utr/", CustomerSellbackConfirmUtrView.as_view()),
    path("gold/sellback/<int:pk>/cancel-upi/", CustomerSellbackCancelUpiView.as_view()),
    path("gold/resolve/", GoldUPIResolveView.as_view()),
    path("gold/transfers/", GoldTransferCreateView.as_view()),
    path("gold/identity/", GoldIdentityUpsertView.as_view()),
    path("gold/default-jeweller/", DefaultJewellerView.as_view()),
    path("gold/pay/<path:gold_upi>/", GoldTransferPublicMetaView.as_view()),
    path("gold-deposit/intakes/", CustomerGoldDepositIntakesView.as_view()),
    path(
        "gold-deposit/intakes/<int:pk>/counter-otp/",
        CustomerGoldDepositCounterOtpIssueView.as_view(),
    ),
    path("jeweller/gold-deposit/intakes/", JewellerGoldDepositIntakeCreateView.as_view()),
    path("jeweller/gold-deposit/pending/", JewellerGoldDepositPendingView.as_view()),
    path(
        "jeweller/gold-deposit/intakes/<int:pk>/verify/",
        JewellerGoldDepositVerifyView.as_view(),
    ),
    path("fractional/quote/", FractionalQuoteView.as_view()),
    path("fractional/orders/", FractionalOrdersView.as_view()),
    path(
        "fractional/orders/<int:pk>/counter-otp/",
        FractionalCounterOtpIssueView.as_view(),
    ),
    path(
        "fractional/counter-otp-policy/",
        FractionalCounterOtpPolicyView.as_view(),
    ),
    path(
        "fractional/orders/<int:pk>/confirm-upi/",
        FractionalOrderConfirmUpiView.as_view(),
    ),
    path(
        "fractional/orders/<int:pk>/payment/",
        FractionalOrderPaymentView.as_view(),
    ),
    path(
        "fractional/orders/<int:pk>/submit-utr/",
        FractionalOrderSubmitUtrView.as_view(),
    ),
    path(
        "fractional/orders/<int:pk>/cancel-upi/",
        FractionalOrderCancelUpiView.as_view(),
    ),
    path("jeweller/fractional/pending/", JewellerFractionalPendingView.as_view()),
    path("jeweller/fractional/pending-upi/", JewellerFractionalPendingUpiView.as_view()),
    path("jeweller/profile/upi/", JewellerUpiProfileView.as_view()),
    path("jeweller/sellbacks/<int:pk>/accept/", JewellerSellbackAcceptView.as_view()),
    path("jeweller/sellbacks/<int:pk>/reject/", JewellerSellbackRejectView.as_view()),
    path("jeweller/sellbacks/<int:pk>/complete/", JewellerSellbackCompleteView.as_view()),
    path("jeweller/sellbacks/<int:pk>/payout/", JewellerSellbackPayoutView.as_view()),
    path("jeweller/sellbacks/<int:pk>/submit-utr/", JewellerSellbackSubmitUtrView.as_view()),
    path("jeweller/portfolio/ledger/", JewellerPortfolioLedgerView.as_view()),
    path("jeweller/loans/", JewellerLoanListView.as_view()),
    path("jeweller/loans/<int:pk>/accept/", JewellerLoanAcceptView.as_view()),
    path("jeweller/loans/<int:pk>/reject/", JewellerLoanRejectView.as_view()),
    path("jeweller/loans/<int:pk>/complete/", JewellerLoanCompleteView.as_view()),
    path("jeweller/loan-repayments/", JewellerLoanRepaymentListView.as_view()),
    path(
        "jeweller/loan-repayments/<int:pk>/accept/",
        JewellerLoanRepaymentAcceptView.as_view(),
    ),
    path(
        "jeweller/loan-repayments/<int:pk>/reject/",
        JewellerLoanRepaymentRejectView.as_view(),
    ),
    path(
        "jeweller/loan-repayments/<int:pk>/complete/",
        JewellerLoanRepaymentCompleteView.as_view(),
    ),
    path("jeweller/sellbacks/", JewellerSellbackListView.as_view()),
    path(
        "jeweller/custody-vaults/<int:customer_id>/ledger/",
        JewellerCustomerVaultLedgerView.as_view(),
    ),
    path("jeweller/custody-vaults/", JewellerCustodyVaultsView.as_view()),
    path(
        "jeweller/fractional/orders/<int:pk>/verify/",
        JewellerFractionalVerifyView.as_view(),
    ),
    path(
        "jeweller/fractional/orders/<int:pk>/confirm-utr/",
        JewellerFractionalConfirmUtrView.as_view(),
    ),
    path("auth/token/refresh/", TokenRefreshView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("kyc/bank/", BankAccountUpsertView.as_view()),
    path("kyc/documents/", KYDocumentListView.as_view()),
    path("kyc/documents/upload/", KYDocumentUploadView.as_view()),
    path("admin/overview/", AdminOverviewView.as_view()),
    path(
        "admin/fractional-counter-otp-policy/",
        AdminFractionalCounterOtpPolicyView.as_view(),
    ),
    path("admin/notifications/", AdminNotificationsListView.as_view()),
    path("admin/notifications/mark-read/", AdminNotificationsMarkReadView.as_view()),
    path(
        "admin/users/<int:user_id>/documents/",
        AdminUserDocumentsView.as_view(),
    ),
    path(
        "admin/users/<int:user_id>/kyc/<str:action>/",
        AdminCustomerKYCActionView.as_view(),
    ),
    path(
        "admin/users/<int:user_id>/kyb/<str:action>/",
        AdminJewellerKYBActionView.as_view(),
    ),
    path(
        "admin/users/<int:user_id>/verification/revoke/",
        AdminVerificationRevokeView.as_view(),
    ),
    path(
        "admin/users/<int:user_id>/documents/<int:doc_id>/request-reupload/",
        AdminDocumentRequestReuploadView.as_view(),
    ),
    path("admin/users/<int:user_id>/freeze/", AdminFreezeUserView.as_view()),
    path("cross-redemption/authorize/", CustomerCrossRedemptionAuthorizeView.as_view()),
    path("cross-redemption/", CustomerCrossRedemptionListView.as_view()),
    path("cross-redemption/<int:pk>/cancel/", CustomerCrossRedemptionCancelView.as_view()),
    path("jeweller/cross-redemption/inbox/", JewellerCrossRedemptionInboxView.as_view()),
    path("jeweller/cross-redemption/initiate/", JewellerCrossRedemptionInitiateView.as_view()),
    path(
        "jeweller/cross-redemption/<int:pk>/destination/accept/",
        JewellerCrossRedemptionDestAcceptView.as_view(),
    ),
    path(
        "jeweller/cross-redemption/<int:pk>/destination/reject/",
        JewellerCrossRedemptionDestRejectView.as_view(),
    ),
    path(
        "jeweller/cross-redemption/<int:pk>/source/request-otp/",
        JewellerCrossRedemptionSourceOtpView.as_view(),
    ),
    path(
        "jeweller/cross-redemption/<int:pk>/source/approve/",
        JewellerCrossRedemptionSourceApproveView.as_view(),
    ),
    path(
        "jeweller/cross-redemption/<int:pk>/source/reject/",
        JewellerCrossRedemptionSourceRejectView.as_view(),
    ),
    path(
        "jeweller/cross-redemption/<int:pk>/fulfillment/heartbeat/",
        JewellerCrossRedemptionFulfillmentHeartbeatView.as_view(),
    ),
    path("admin/cross-redemption/", AdminCrossRedemptionListView.as_view()),
    path(
        "admin/cross-redemption/<int:pk>/risk-block/",
        AdminCrossRedemptionRiskBlockView.as_view(),
    ),
    path(
        "admin/cross-redemption/<int:pk>/settlement-complete/",
        AdminCrossRedemptionSettlementCompleteView.as_view(),
    ),
]
