# Generated by Django 5.2.13 on 2026-05-12 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_cridora_ids(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for u in User.objects.all().order_by("pk"):
        if u.cridora_member_id:
            continue
        u.cridora_member_id = f"CRI{u.pk:010d}"
        u.save(update_fields=["cridora_member_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cridora_member_id',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Permanent platform id (CRI…); assigned on first save.',
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='default_jeweller',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='gold_handle_local',
            field=models.CharField(blank=True, help_text='GoldUPI local part before @ (alphanumeric / underscore).', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='gold_upi',
            field=models.CharField(blank=True, help_text='Normalized GoldUPI username@jewellercode (lowercase).', max_length=130, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jeweller_code',
            field=models.CharField(blank=True, help_text='Public storefront slug for KYB-verified jewellers (GoldUPI suffix).', max_length=40),
        ),
        migrations.CreateModel(
            name='GoldBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_grams', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold balance',
            },
        ),
        migrations.CreateModel(
            name='GoldTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=6, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_custodian', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_custodian_from', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transfers_out', to=settings.AUTH_USER_MODEL)),
                ('to_custodian', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_custodian_to', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transfers_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(_backfill_cridora_ids, migrations.RunPython.noop),
    ]
