# Generated by Django 5.2.13 on 2026-05-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gold_upi_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractionalGoldPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_rate_inr_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grams', models.DecimalField(decimal_places=6, max_digits=16)),
                ('gold_value_inr_pre_gst', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=3, default=3, max_digits=6)),
                ('gst_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('counter', 'Pay at counter')], max_length=16)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('awaiting_counter', 'Awaiting counter confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=24)),
                ('jeweller_verified_at', models.DateTimeField(blank=True, null=True)),
                ('customer_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractional_purchases', to=settings.AUTH_USER_MODEL)),
                ('jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='fractional_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
