# Generated by Django 5.2.13 on 2026-05-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_webpushsubscription'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webpushsubscription',
            name='acc_wpush_user_idx',
        ),
    ]
