# Generated by Django 5.2.13 on 2026-05-14 10:37

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum


def forwards_migrate_gold_balance_into_vaults(apps, schema_editor):
    GoldBalance = apps.get_model("accounts", "GoldBalance")
    GoldVault = apps.get_model("accounts", "GoldVault")
    VaultHolding = apps.get_model("accounts", "VaultHolding")
    frac = "fractional"

    for gb in GoldBalance.objects.select_related("user").iterator():
        u = gb.user
        if getattr(u, "user_type", "") != "customer":
            continue
        dj_id = getattr(u, "default_jeweller_id", None)
        amt = gb.balance_grams or Decimal("0")
        if not dj_id or amt <= 0:
            continue
        vault, _ = GoldVault.objects.get_or_create(
            owner_id=u.pk, custodian_id=dj_id
        )
        holding, _ = VaultHolding.objects.get_or_create(
            vault=vault,
            holding_type=frac,
            defaults={"balance_grams": Decimal("0")},
        )
        VaultHolding.objects.filter(pk=holding.pk).update(balance_grams=amt)

    owner_ids = GoldVault.objects.values_list("owner_id", flat=True).distinct()
    for uid in owner_ids:
        total = VaultHolding.objects.filter(
            vault__owner_id=uid,
            holding_type=frac,
        ).aggregate(t=Sum("balance_grams"))["t"]
        if total is None:
            total = Decimal("0")
        gb = GoldBalance.objects.filter(user_id=uid).first()
        if gb:
            GoldBalance.objects.filter(pk=gb.pk).update(balance_grams=total)


def noop_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_webpushsubscription_acc_wpush_user_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(db_index=True, max_length=16)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='jeweller_pref_nearby',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_pref_for_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='jeweller_pref_ornament',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ornament_pref_for_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='jeweller_pref_redemption',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_pref_for_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kydocument',
            name='doc_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar card'), ('pan', 'PAN card'), ('selfie_photo', 'Live selfie / photograph'), ('pan_business', 'Business PAN'), ('gst_certificate', 'GST registration certificate'), ('shop_establishment', 'Shop & Establishment registration'), ('trade_license', 'Municipal trade / shop license'), ('bis_hallmark', 'BIS hallmark license / registration'), ('incorporation_certificate', 'Certificate of incorporation (Company)'), ('partnership_deed', 'Partnership deed / LLP agreement'), ('address_proof_shop', 'Business address proof'), ('proprietor_aadhaar', 'Proprietor / partner Aadhaar'), ('proprietor_pan', 'Proprietor / partner PAN'), ('msme_udyam', 'MSME Udyam registration (optional)'), ('iec_import_export', 'IEC (import-export code, if applicable)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_jeweller',
            field=models.ForeignKey(blank=True, help_text='Primary default jeweller (routing, transfers, marketplace).', limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GoldVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_public_id', models.CharField(blank=True, help_text='Public routing ID, e.g. rahul4821.goldhousekochi@cridora', max_length=160, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custodian', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='gold_vaults_custodied', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='gold_vaults_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_type', models.CharField(choices=[('fractional', 'Fractional gold'), ('deposit', 'Gold deposit'), ('golden_scheme', 'Golden scheme')], default='fractional', max_length=24)),
                ('balance_grams', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.goldvault')),
            ],
        ),
        migrations.AddConstraint(
            model_name='goldvault',
            constraint=models.UniqueConstraint(fields=('owner', 'custodian'), name='uniq_goldvault_owner_custodian'),
        ),
        migrations.AddConstraint(
            model_name='vaultholding',
            constraint=models.UniqueConstraint(fields=('vault', 'holding_type'), name='uniq_vault_holding_type'),
        ),
        migrations.RunPython(forwards_migrate_gold_balance_into_vaults, noop_migration),
    ]
