# Generated by Django migration

from django.db import migrations, models
import django.core.validators


def _seed_platform_operational_settings(apps, schema_editor):
    PlatformOperationalSettings = apps.get_model("accounts", "PlatformOperationalSettings")
    PlatformOperationalSettings.objects.get_or_create(
        pk=1,
        defaults={"fractional_counter_otp_ttl_seconds": 900},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_fractional_counter_otp_and_liability"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformOperationalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fractional_counter_otp_ttl_seconds",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="Counter fractional OTP validity window (60–86400 seconds).",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform operational settings",
                "verbose_name_plural": "Platform operational settings",
            },
        ),
        migrations.RunPython(_seed_platform_operational_settings, migrations.RunPython.noop),
    ]
