# Generated by Django — festival broadcast schedules

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_platform_operational_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalBroadcastNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Cridora",
                        help_text="Notification title shown on the device.",
                        max_length=120,
                    ),
                ),
                ("body", models.TextField(help_text="Main message body.")),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text=(
                            "When to send (UTC in DB; use aware datetimes from the API)."
                        ),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "push_recipient_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text=(
                            "Number of push endpoints successfully targeted when sent."
                        ),
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="festival_broadcasts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
