# Generated by Django 5.2.13 on 2026-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_festivalbroadcastnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='kind',
            field=models.CharField(choices=[('kyc_upload', 'Customer KYC upload'), ('kyb_upload', 'Jeweller KYB upload'), ('festival_broadcast_sent', 'Festival broadcast sent')], max_length=32),
        ),
    ]
