# Generated by Django 5.2.13 on 2026-05-15 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_admin_notification_festival_broadcast_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
