# Generated by Django 5.2.13 on 2026-05-16 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sellback_workflow_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalGoldHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_type', models.CharField(choices=[('personal', 'Personal')], default='personal', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ornament', 'Ornament'), ('coin', 'Coin'), ('bar', 'Bar'), ('other', 'Other')], max_length=24)),
                ('weight_grams', models.DecimalField(decimal_places=6, max_digits=16)),
                ('purity', models.CharField(default='BIS 916', max_length=64)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_source', models.CharField(blank=True, max_length=512)),
                ('estimated_current_value_inr', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot at last save: reference 22K ₹/g × weight (MVP).', max_digits=18)),
                ('is_self_declared', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('self_declared', 'Self declared'), ('jeweller_added', 'Jeweller added'), ('verified', 'Verified')], default='self_declared', max_length=24)),
                ('created_by_type', models.CharField(choices=[('user', 'User'), ('jeweller', 'Jeweller'), ('admin', 'Admin')], max_length=16)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_removed', models.BooleanField(db_index=True, default=False)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jeweller', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_holdings_added_for_customers', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_holdings_removed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_gold_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalHoldingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('purchase_invoice', 'Purchase invoice'), ('gold_certificate', 'Gold certificate'), ('purity_certificate', 'Purity certificate'), ('valuation_document', 'Valuation document'), ('warranty_card', 'Warranty card'), ('product_image', 'Product image'), ('other', 'Other')], max_length=32)),
                ('file', models.FileField(upload_to='personal_holding_docs/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_by_type', models.CharField(choices=[('user', 'User'), ('jeweller', 'Jeweller'), ('admin', 'Admin')], max_length=16)),
                ('uploaded_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=120)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.personalgoldholding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalPortfolioAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(blank=True, max_length=16)),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('holding_create', 'Holding created'), ('holding_update', 'Holding updated'), ('holding_delete', 'Holding deleted'), ('document_upload', 'Document uploaded'), ('document_delete', 'Document deleted'), ('jeweller_add', 'Jeweller added holding'), ('admin_remove', 'Admin removed'), ('verification_change', 'Verification changed')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.personalholdingdocument')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.personalgoldholding')),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_portfolio_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('holding_added', 'Holding added'), ('jeweller_added_holding', 'Jeweller added holding'), ('document_uploaded', 'Document uploaded'), ('verification_updated', 'Verification updated')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('link_path', models.CharField(blank=True, max_length=512)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personalgoldholding',
            index=models.Index(fields=['user', 'is_removed'], name='accounts_pe_user_id_d82413_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliousernotification',
            index=models.Index(fields=['user', 'read_at'], name='accounts_po_user_id_f02989_idx'),
        ),
    ]
