# Generated by Django 5.2.13 on 2026-05-16 19:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_personal_holdings_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalgoldholding',
            name='weight_grams',
            field=models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
