# Generated by Django 5.x migration

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_personal_holding_purchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldDepositIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grams", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "purity_karat",
                    models.CharField(
                        default="22",
                        help_text="Declared purity (e.g. 22, 916 BIS) after verification.",
                        max_length=32,
                    ),
                ),
                (
                    "reference_metal_inr_per_gram",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Jeweller reference 22K metal ₹/g at intake.",
                        max_digits=12,
                    ),
                ),
                (
                    "estimated_value_inr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="grams × reference rate (indicative).",
                        max_digits=16,
                    ),
                ),
                ("jeweller_note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_customer_otp", "Awaiting customer OTP"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="awaiting_customer_otp",
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_deposit_intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jeweller",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "jeweller"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_deposit_intakes_as_jeweller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoldDepositCounterOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intake",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_otp",
                        to="accounts.golddepositintake",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jewellerliabilityledgerentry",
            name="gold_deposit_intake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liability_entries",
                to="accounts.golddepositintake",
            ),
        ),
        migrations.AlterField(
            model_name="jewellerliabilityledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fractional_credit", "Fractional credit"),
                    ("sellback_release", "Sellback release"),
                    ("deposit_credit", "Gold deposit credit"),
                ],
                default="fractional_credit",
                max_length=32,
            ),
        ),
    ]
