# Generated by Django 5.2.13 on 2026-05-17 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_gold_deposit_intake'),
        ('marketplace', '0021_gold_ticker_reference_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellerliabilityledgerentry',
            name='kind',
            field=models.CharField(choices=[('fractional_credit', 'Fractional credit'), ('sellback_release', 'Sellback release'), ('deposit_credit', 'Gold deposit credit'), ('redemption_purchase_release', 'Vault redemption purchase')], default='fractional_credit', max_length=32),
        ),
        migrations.CreateModel(
            name='VaultProductRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('grams_charged', models.DecimalField(decimal_places=6, max_digits=16)),
                ('final_invoice_inr', models.DecimalField(decimal_places=2, max_digits=16)),
                ('jeweller_subtotal_inr', models.DecimalField(decimal_places=2, max_digits=16)),
                ('metal_rate_inr_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('same_store_checkout', models.BooleanField(default=False)),
                ('cross_platform_fee_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='vault_product_redemptions', to=settings.AUTH_USER_MODEL)),
                ('jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='vault_product_redemptions_as_jeweller', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_redemptions', to='marketplace.marketplaceproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jewellerliabilityledgerentry',
            name='vault_product_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_entries', to='accounts.vaultproductredemption'),
        ),
    ]
