# Generated by Django 5.2.13 on 2026-05-17 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_vault_product_redemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('message_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jewellerliabilityledgerentry',
            name='kind',
            field=models.CharField(choices=[('fractional_credit', 'Fractional credit'), ('sellback_release', 'Sellback release'), ('deposit_credit', 'Gold deposit credit'), ('redemption_purchase_release', 'Vault redemption purchase'), ('cross_redemption_source_release', 'Cross redemption source release'), ('cross_redemption_dest_assume', 'Cross redemption destination assume')], default='fractional_credit', max_length=32),
        ),
        migrations.CreateModel(
            name='CrossRedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=6, max_digits=16)),
                ('estimated_value_snapshot_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('lifecycle_stage', models.CharField(choices=[('auth', 'Auth'), ('fulfillment', 'Fulfillment'), ('settlement', 'Settlement'), ('closed', 'Closed')], default='auth', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], max_length=16, null=True)),
                ('close_reason_code', models.CharField(blank=True, choices=[('timeout', 'Timeout'), ('reject', 'Reject'), ('risk_block', 'Risk block'), ('user_cancel', 'User cancel'), ('system_kill_switch', 'System kill switch')], max_length=32, null=True)),
                ('workflow_state', models.CharField(choices=[('awaiting_destination', 'Awaiting destination'), ('awaiting_source', 'Awaiting source'), ('saga_pending', 'Saga pending'), ('saga_done', 'Saga done')], default='awaiting_destination', max_length=32)),
                ('ux_lane', models.CharField(blank=True, default='', help_text='instant | delayed — drives public UX mapping only.', max_length=16)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('lease_holder', models.CharField(blank=True, default='', max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('checkpoint_seq', models.PositiveIntegerField(default=0)),
                ('last_completed_step', models.CharField(blank=True, default='', max_length=64)),
                ('saga_status', models.CharField(choices=[('idle', 'Idle'), ('in_progress', 'In progress'), ('committed', 'Committed'), ('compensating', 'Compensating'), ('aborted', 'Aborted')], default='idle', max_length=20)),
                ('fulfillment_committed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_redemption_requests_as_destination', to=settings.AUTH_USER_MODEL)),
                ('source_jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_redemption_requests_as_source', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_redemption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossRedemptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('user', 'User'), ('jeweller_source', 'Jeweller source'), ('jeweller_dest', 'Jeweller destination'), ('system', 'System'), ('admin', 'Admin')], max_length=20)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.crossredemptionrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='jewellerliabilityledgerentry',
            name='cross_redemption_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_entries', to='accounts.crossredemptionrequest'),
        ),
        migrations.CreateModel(
            name='CrossRedemptionSagaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('fwd', 'Forward'), ('rev', 'Reverse')], max_length=8)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saga_steps', to='accounts.crossredemptionrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExposureReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_value_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('consumed', 'Consumed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_exposure_reservations_as_dest', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_reservation', to='accounts.crossredemptionrequest')),
                ('source_jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_exposure_reservations_as_source', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JewellerCrossPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_source_approval', models.BooleanField(default=False)),
                ('instant_enabled', models.BooleanField(default=False)),
                ('allow_cross_redemption', models.BooleanField(default=True)),
                ('trust_tier', models.PositiveSmallIntegerField(default=0)),
                ('settlement_delay_hours', models.PositiveIntegerField(default=24)),
                ('max_daily_exposure_inr', models.DecimalField(decimal_places=2, default=500000, max_digits=18)),
                ('max_pending_liability_inr', models.DecimalField(decimal_places=2, default=10000000, max_digits=18)),
                ('reserve_balance_inr', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('risk_multiplier', models.DecimalField(decimal_places=2, default=3, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jeweller', models.OneToOneField(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_redemption_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jeweller cross-redemption policy',
            },
        ),
        migrations.CreateModel(
            name='SettlementObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('grams_equivalent', models.DecimalField(decimal_places=6, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='accounts.settlementbatch')),
                ('from_jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_obligations_from', to=settings.AUTH_USER_MODEL)),
                ('linked_requests', models.ManyToManyField(blank=True, related_name='settlement_obligations', to='accounts.crossredemptionrequest')),
                ('to_jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_obligations_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crossredemptionrequest',
            index=models.Index(fields=['deadline_at', 'lifecycle_stage'], name='accounts_cr_deadlin_8ef0da_idx'),
        ),
        migrations.AddIndex(
            model_name='crossredemptionrequest',
            index=models.Index(fields=['destination_jeweller', 'workflow_state'], name='accounts_cr_destina_458cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='crossredemptionrequest',
            index=models.Index(fields=['source_jeweller', 'workflow_state'], name='accounts_cr_source__4aff54_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementobligation',
            index=models.Index(fields=['status', 'from_jeweller'], name='accounts_se_status_721678_idx'),
        ),
    ]
