# Generated by Django 5.2.13 on 2026-05-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_cross_redemption_financial_saga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellerliabilityledgerentry',
            name='kind',
            field=models.CharField(choices=[('fractional_credit', 'Fractional credit'), ('sellback_release', 'Sellback release'), ('deposit_credit', 'Gold deposit credit'), ('redemption_purchase_release', 'Vault redemption purchase'), ('cross_redemption_source_release', 'Cross redemption source release'), ('cross_redemption_dest_assume', 'Cross redemption destination assume'), ('cr_xr_src_rel_rb', 'Cross redemption source rollback'), ('cr_xr_dst_asm_rb', 'Cross redemption dest rollback')], default='fractional_credit', max_length=32),
        ),
    ]
