# Generated by Django 5.2.13 on 2026-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldloanrequest',
            name='reference_metal_inr_per_gram_snapshot',
            field=models.DecimalField(decimal_places=2, help_text='Jeweller reference 22K metal ₹/g at quote time.', max_digits=12),
        ),
    ]
