# Generated by Django 5.2.13 on 2026-05-19 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_gold_loan_repayment_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellerliabilityledgerentry',
            name='kind',
            field=models.CharField(choices=[('fractional_credit', 'Fractional credit'), ('sellback_release', 'Sellback release'), ('deposit_credit', 'Gold deposit credit'), ('redemption_purchase_release', 'Vault redemption purchase'), ('cross_redemption_source_release', 'Cross redemption source release'), ('cross_redemption_dest_assume', 'Cross redemption destination assume'), ('cr_xr_src_rel_rb', 'Cross redemption source rollback'), ('cr_xr_dst_asm_rb', 'Cross redemption dest rollback'), ('corridorapay_release', 'CridoraPay vault release')], default='fractional_credit', max_length=32),
        ),
        migrations.CreateModel(
            name='CridoraPayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shop purchase', max_length=255)),
                ('category', models.CharField(default='ornament', max_length=24)),
                ('weight_grams', models.DecimalField(decimal_places=6, max_digits=16)),
                ('purity', models.CharField(default='BIS 916', max_length=64)),
                ('total_inr', models.DecimalField(decimal_places=2, max_digits=16)),
                ('metal_rate_inr_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jeweller_note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('awaiting_customer', 'Awaiting customer'), ('upi_pending', 'UPI pending'), ('vault_otp_pending', 'Vault OTP pending'), ('cash_pending', 'Cash pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='awaiting_customer', max_length=32)),
                ('payment_method', models.CharField(blank=True, choices=[('vault', 'Vault'), ('upi', 'UPI')], default='', max_length=16)),
                ('vault_grams_chosen', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('vault_inr_applied', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cash_payable_inr', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vault_debited', models.BooleanField(default=False)),
                ('payee_upi_vpa', models.CharField(blank=True, default='', max_length=128)),
                ('payment_note', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='cridorapay_bills', to=settings.AUTH_USER_MODEL)),
                ('jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cridorapay_bills_as_jeweller', to=settings.AUTH_USER_MODEL)),
                ('personal_holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cridorapay_bills', to='accounts.personalgoldholding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jewellerliabilityledgerentry',
            name='corridorapay_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_entries', to='accounts.cridorapaybill'),
        ),
        migrations.CreateModel(
            name='CridoraPayOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_otp', to='accounts.cridorapaybill')),
            ],
            options={
                'verbose_name': 'CridoraPay OTP',
            },
        ),
    ]
