# Generated by Django 5.2.13 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_corridorapay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cridorapaybill',
            name='purchase_invoice',
            field=models.FileField(blank=True, upload_to='cridorapay_invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cridorapaybill',
            name='purchase_invoice_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
