# Generated by Django migration

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_cridorapay_purchase_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformoperationalsettings",
            name="fractional_markup_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Platform markup on fractional purchase metal rate (0–100%).",
                max_digits=8,
                validators=[
                    MinValueValidator(Decimal("0")),
                    MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
