# Generated by Django 5.2.13 on 2026-05-24 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_platform_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcommercialledgerentry',
            name='vault_product_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_commercial_entries', to='accounts.vaultproductredemption'),
        ),
        migrations.AlterField(
            model_name='platformcommercialledgerentry',
            name='fractional_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_commercial_entries', to='accounts.fractionalgoldpurchase'),
        ),
        migrations.AlterField(
            model_name='platformcommercialledgerentry',
            name='kind',
            field=models.CharField(choices=[('spread_fee', 'Spread fee'), ('cross_platform_fee', 'Cross-platform fee')], default='spread_fee', max_length=32),
        ),
        migrations.CreateModel(
            name='PlatformSettlementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('jeweller_to_platform', 'Jeweller to platform'), ('platform_to_jeweller', 'Platform to jeweller')], max_length=32)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending_proof', 'Pending proof'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_proof', max_length=32)),
                ('receipt_file', models.FileField(blank=True, upload_to='settlement_receipts/%Y/%m/')),
                ('reference_note', models.CharField(blank=True, max_length=256)),
                ('utr', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settlement_payments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('jeweller', models.ForeignKey(limit_choices_to={'user_type': 'jeweller'}, on_delete=django.db.models.deletion.CASCADE, related_name='platform_settlement_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settlement_payments_paid', to=settings.AUTH_USER_MODEL)),
                ('settlement_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.platformsettlementbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
