# Generated by Django 5.2.13 on 2026-05-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_platform_commercial_ornament_fee_and_settlement_payments'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cridorapaybill',
            name='upi_fraud_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cridorapaybill',
            name='upi_last_rejection_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cridorapaybill',
            name='upi_proof_file',
            field=models.FileField(blank=True, upload_to='upi_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cridorapaybill',
            name='upi_rejection_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cridorapaybill',
            name='upi_utr',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cridorapaybill',
            name='utr_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fractionalgoldpurchase',
            name='upi_fraud_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fractionalgoldpurchase',
            name='upi_last_rejection_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fractionalgoldpurchase',
            name='upi_proof_file',
            field=models.FileField(blank=True, upload_to='upi_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='fractionalgoldpurchase',
            name='upi_rejection_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldloanrepaymentrequest',
            name='upi_fraud_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldloanrepaymentrequest',
            name='upi_last_rejection_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goldloanrepaymentrequest',
            name='upi_proof_file',
            field=models.FileField(blank=True, upload_to='upi_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='goldloanrepaymentrequest',
            name='upi_rejection_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldsellbackrequest',
            name='upi_fraud_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldsellbackrequest',
            name='upi_last_rejection_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goldsellbackrequest',
            name='upi_proof_file',
            field=models.FileField(blank=True, upload_to='upi_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='goldsellbackrequest',
            name='upi_rejection_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettlementpayment',
            name='upi_fraud_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettlementpayment',
            name='upi_last_rejection_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformsettlementpayment',
            name='upi_rejection_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cridorapaybill',
            name='status',
            field=models.CharField(choices=[('awaiting_customer', 'Awaiting customer'), ('upi_pending', 'UPI pending'), ('vault_otp_pending', 'Vault OTP pending'), ('cash_pending', 'Cash pending'), ('pending_review', 'Pending jeweller review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('proof_rejected', 'Proof rejected — reupload required'), ('on_hold', 'On hold — visit jeweller')], default='awaiting_customer', max_length=32),
        ),
        migrations.AlterField(
            model_name='fractionalgoldpurchase',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('signal_received', 'Payment signal received'), ('awaiting_counter', 'Awaiting counter confirmation'), ('awaiting_utr_verify', 'Awaiting UTR verification'), ('pending_review', 'Pending jeweller review'), ('needs_manual_verification', 'Needs manual verification'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('proof_rejected', 'Proof rejected — reupload required'), ('on_hold', 'On hold — visit jeweller')], default='pending_payment', max_length=32),
        ),
        migrations.AlterField(
            model_name='goldloanrepaymentrequest',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending UPI payment'), ('signal_received', 'Payment signal received'), ('pending_jeweller', 'Pending jeweller'), ('pending_review', 'Pending jeweller review'), ('needs_manual_verification', 'Needs manual verification'), ('rejected', 'Rejected'), ('accepted_awaiting_otp', 'Accepted awaiting OTP'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('proof_rejected', 'Proof rejected — reupload required'), ('on_hold', 'On hold — visit jeweller')], default='pending_jeweller', max_length=32),
        ),
        migrations.AlterField(
            model_name='goldsellbackrequest',
            name='status',
            field=models.CharField(choices=[('pending_jeweller', 'Pending jeweller'), ('rejected', 'Rejected'), ('accepted_awaiting_otp', 'Accepted awaiting OTP'), ('awaiting_utr_verify', 'Awaiting UTR verification'), ('pending_review', 'Pending customer review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('proof_rejected', 'Proof rejected — reupload required'), ('on_hold', 'On hold — visit customer')], default='pending_jeweller', max_length=32),
        ),
        migrations.CreateModel(
            name='UpiFraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed')], default='open', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_fraud_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_fraud_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='accounts_up_content_fd6d3d_idx'), models.Index(fields=['status', '-created_at'], name='accounts_up_status_092d82_idx')],
            },
        ),
        migrations.CreateModel(
            name='UpiPaymentProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('proof_kind', models.CharField(choices=[('utr', 'UTR'), ('screenshot', 'Screenshot')], max_length=16)),
                ('utr', models.CharField(blank=True, max_length=32)),
                ('proof_file', models.FileField(blank=True, upload_to='upi_proofs/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_remark', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_proof_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='accounts_up_content_c40daa_idx')],
            },
        ),
    ]
