# Generated by Django 5.2.13 on 2026-05-29 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_jeweller_referral_onboarding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationeventlog',
            new_name='accounts_no_event_t_ded952_idx',
            old_name='accounts_no_event_t_6e8b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationeventlog',
            new_name='accounts_no_user_id_8ca438_idx',
            old_name='accounts_no_user_id_8f3c2d_idx',
        ),
        migrations.AlterField(
            model_name='festivalbroadcastnotification',
            name='created_by_jeweller',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeweller_campaign_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfoliousernotification',
            name='jeweller',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'jeweller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
