# Generated by Django 5.2.13 on 2026-05-30 19:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_rename_accounts_no_event_t_6e8b0a_idx_accounts_no_event_t_ded952_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHoldingNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_value_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('holding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_state', to='accounts.personalgoldholding')),
            ],
            options={
                'verbose_name_plural': 'Personal holding notification states',
            },
        ),
        migrations.CreateModel(
            name='UserPortfolioNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_gain_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_notification_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
