# Generated by Django 5.2.13 on 2026-06-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_push_delivery_analytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdeliveryattempt',
            new_name='accounts_pu_status_2d0026_idx',
            old_name='accounts_pu_status__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdeliveryattempt',
            new_name='accounts_pu_user_id_5fa47e_idx',
            old_name='accounts_pu_user_id__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdeliveryattempt',
            new_name='accounts_pu_portfol_76bf1a_idx',
            old_name='accounts_pu_portfol__g7h8i9_idx',
        ),
    ]
