# Generated by Django 5.2.13 on 2026-06-24 03:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_system_notification_messages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientdevicesession',
            new_name='accounts_cl_surface_29148e_idx',
            old_name='accounts_cl_surface_8a1f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdevicesession',
            new_name='accounts_cl_push_re_bb2d11_idx',
            old_name='accounts_cl_push_re_4c2b91_idx',
        ),
        migrations.AlterField(
            model_name='festivalbroadcastnotification',
            name='target_type',
            field=models.CharField(choices=[('ALL_APP_INSTALLS', 'Everyone with alerts on'), ('ALL_USERS', 'Signed-in customers only'), ('SPECIFIC_JEWELLER_USERS', 'Jeweller customers'), ('DEFAULT_JEWELLER_USERS', 'Default jeweller customers'), ('SPECIFIC_USERS', 'Specific users')], default='ALL_USERS', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformoperationalsettings',
            name='gst_on_making_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('5'), help_text='GST % on jewellery making charges.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
