import type { JewellerStorefrontDTO } from '@/lib/marketplaceApi'

const DEMO_PLATFORM_BASE = '7320.00'

function demoBase(overrides: Partial<JewellerStorefrontDTO>): JewellerStorefrontDTO {
  return {
    id: 0,
    business_name: '',
    city: '',
    state: '',
    shop_address: '',
    gstin: '',
    kyc_status: 'verified',
    jeweller_metal_rate_last_updated_at: '2026-05-01T10:30:00+05:30',
    jeweller_store_22k_inr_per_gram: DEMO_PLATFORM_BASE,
    gold_rate_source: 'live_cridora',
    representative_making_charge_inr_per_gram: '0',
    buyback_indicative_inr_per_gram: '0',
    buyback_uses_headline_override: false,
    reference_metal_inr_per_gram: '0',
    gold_deposit_yield_apr_percent: '0',
    gold_loan_interest_apr_percent: '0',
    gold_deposit_note: '',
    default_gold_markup_percent: '0',
    sellback_deduction_percent: '0',
    sellback_fixed_inr_per_gram: '0',
    approved_listing_count: 0,
    logo_url: '',
    credibility_score: '',
    lock_in_summary: '',
    minimum_redeemable_grams: '',
    same_store_mc_benefit: '',
    cross_redemption_fee_note: '',
    metric_active_users: 0,
    metric_total_redeemed_gold_grams: '0',
    metric_years_active: '0',
    feat_instant_redemption: false,
    feat_zero_mc_same_store: false,
    feat_loan_available: false,
    feat_goldnest_available: false,
    feat_emergency_funds: false,
    feat_cross_redemption: true,
    ...overrides,
  }
}

/**
 * Offline / illustration rows aligned with `seed_test_users` dummy jewellers + primary test jeweller.
 * Negative IDs: no public storefront route; merge skips a row when the API returns the same business_name.
 */
export const JEWELLER_MARKETPLACE_DEMO_ROWS: JewellerStorefrontDTO[] = [
  demoBase({
    id: -1,
    business_name: 'Demo Gold House — Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    shop_address: '12-2-823, S.R. Nagar',
    gstin: '36AABCT1332B1Z5',
    representative_making_charge_inr_per_gram: '720',
    buyback_indicative_inr_per_gram: '7055.62',
    reference_metal_inr_per_gram: '7335.33',
    gold_deposit_yield_apr_percent: '5.500',
    gold_loan_interest_apr_percent: '0',
    gold_deposit_note:
      'Vault gold credited to this showroom settles per Cridora ledger (T+1). Indicative sellback uses the rates shown on each listing.',
    default_gold_markup_percent: '1.250',
    sellback_deduction_percent: '2.000',
    sellback_fixed_inr_per_gram: '15.00',
    approved_listing_count: 3,
    logo_url: 'https://images.unsplash.com/photo-1610375461245-83b9cb88779c?w=120&h=120&fit=crop',
    credibility_score: '88.40',
    lock_in_summary: '15 / 30 / 90 days · none optional',
    minimum_redeemable_grams: '0.250',
    same_store_mc_benefit: '0% MC same store on ornament redeem',
    cross_redemption_fee_note: '~1.2% platform + GST on MC',
    metric_active_users: 1240,
    metric_total_redeemed_gold_grams: '312.450',
    metric_years_active: '12.0',
    feat_instant_redemption: true,
    feat_zero_mc_same_store: true,
    feat_loan_available: true,
    feat_goldnest_available: true,
    feat_emergency_funds: true,
    feat_cross_redemption: true,
  }),
  demoBase({
    id: -2,
    business_name: 'Heritage Bay Jewellers — Kochi',
    city: 'Kochi',
    state: 'Kerala',
    shop_address: 'MG Road, next to Tower',
    gstin: '32AABCU9603R1ZX',
    representative_making_charge_inr_per_gram: '680',
    buyback_indicative_inr_per_gram: '7176.73',
    reference_metal_inr_per_gram: '7303.06',
    gold_deposit_yield_apr_percent: '6.000',
    gold_loan_interest_apr_percent: '0',
    gold_deposit_note: 'Illustrative deposit yield on this demo storefront — not live pricing.',
    default_gold_markup_percent: '0.800',
    sellback_deduction_percent: '1.500',
    sellback_fixed_inr_per_gram: '12.00',
    approved_listing_count: 3,
    credibility_score: '91.00',
    lock_in_summary: '30 days default',
    minimum_redeemable_grams: '0.500',
    same_store_mc_benefit: '50% MC reduction same store',
    cross_redemption_fee_note: 'Cross redeem: flat MC + platform fee',
    metric_active_users: 890,
    metric_total_redeemed_gold_grams: '205.100',
    metric_years_active: '18.5',
    feat_instant_redemption: true,
    feat_zero_mc_same_store: false,
    feat_loan_available: true,
    feat_goldnest_available: true,
    feat_emergency_funds: false,
    feat_cross_redemption: true,
  }),
  demoBase({
    id: -3,
    business_name: 'Metro Gold Palace — Mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    shop_address: 'Linking Road, Bandra West',
    gstin: '27AABCU9603R1ZX',
    representative_making_charge_inr_per_gram: '920',
    buyback_indicative_inr_per_gram: '7022.94',
    reference_metal_inr_per_gram: '7324.62',
    gold_deposit_yield_apr_percent: '4.750',
    gold_loan_interest_apr_percent: '8.5',
    gold_deposit_note: 'Locker-linked deposits and loan APRs are illustrative for this demo storefront.',
    default_gold_markup_percent: '1.100',
    sellback_deduction_percent: '2.250',
    sellback_fixed_inr_per_gram: '18.00',
    approved_listing_count: 3,
    credibility_score: '84.25',
    lock_in_summary: '12 months max · flexible',
    minimum_redeemable_grams: '1.000',
    same_store_mc_benefit: 'Flat ₹499 MC select bridal',
    cross_redemption_fee_note: '2% cross fee + MC',
    metric_active_users: 2100,
    metric_total_redeemed_gold_grams: '890.000',
    metric_years_active: '6.0',
    feat_instant_redemption: false,
    feat_zero_mc_same_store: false,
    feat_loan_available: true,
    feat_goldnest_available: false,
    feat_emergency_funds: true,
    feat_cross_redemption: true,
  }),
  demoBase({
    id: -4,
    business_name: 'Garden City Ornaments — Bengaluru',
    city: 'Bengaluru',
    state: 'Karnataka',
    shop_address: 'Koramangala 5th Block',
    gstin: '29AABCU9603R1ZX',
    representative_making_charge_inr_per_gram: '790',
    buyback_indicative_inr_per_gram: '7040.81',
    reference_metal_inr_per_gram: '7360.87',
    gold_deposit_yield_apr_percent: '5.250',
    gold_loan_interest_apr_percent: '0',
    gold_deposit_note: 'Demo storefront — compare rates and disclosures with other partner cards.',
    default_gold_markup_percent: '1.600',
    sellback_deduction_percent: '1.800',
    sellback_fixed_inr_per_gram: '14.50',
    approved_listing_count: 3,
    credibility_score: '86.00',
    lock_in_summary: 'None on fractional',
    minimum_redeemable_grams: '0.100',
    same_store_mc_benefit: '0% MC · loyalty tier',
    cross_redemption_fee_note: 'Standard cross-jeweller schedule',
    metric_active_users: 1560,
    metric_total_redeemed_gold_grams: '410.880',
    metric_years_active: '9.5',
    feat_instant_redemption: true,
    feat_zero_mc_same_store: true,
    feat_loan_available: true,
    feat_goldnest_available: true,
    feat_emergency_funds: true,
    feat_cross_redemption: true,
  }),
]

function normName(s: string): string {
  return s.trim().toLowerCase()
}

/** API rows win when business_name matches a demo (live data replaces preview). */
export function mergeJewellerListWithDemos(apiRows: JewellerStorefrontDTO[]): JewellerStorefrontDTO[] {
  const normalizedApi = apiRows.map((r) => ({
    ...r,
    logo_url: r.logo_url ?? '',
    credibility_score: r.credibility_score ?? '',
    lock_in_summary: r.lock_in_summary ?? '',
    minimum_redeemable_grams: r.minimum_redeemable_grams ?? '',
    same_store_mc_benefit: r.same_store_mc_benefit ?? '',
    cross_redemption_fee_note: r.cross_redemption_fee_note ?? '',
    metric_active_users: r.metric_active_users ?? 0,
    metric_total_redeemed_gold_grams: r.metric_total_redeemed_gold_grams ?? '0',
    metric_years_active: r.metric_years_active ?? '0',
    feat_instant_redemption: Boolean(r.feat_instant_redemption),
    feat_zero_mc_same_store: Boolean(r.feat_zero_mc_same_store),
    feat_loan_available: Boolean(r.feat_loan_available),
    feat_goldnest_available: Boolean(r.feat_goldnest_available),
    feat_emergency_funds: Boolean(r.feat_emergency_funds),
    feat_cross_redemption: r.feat_cross_redemption !== false,
  }))
  const names = new Set(normalizedApi.map((r) => normName(r.business_name)))
  const extras = JEWELLER_MARKETPLACE_DEMO_ROWS.filter((d) => !names.has(normName(d.business_name)))
  return [...normalizedApi, ...extras]
}
